name: xTeam
main: me.protocos.xteam.XTeam
version: 1.8.1
author: protocos
softdepend: [PermissionsEx, SQLibrary]
commands:
    team:
        description: Team commands
        usage: /<command>
        aliases: [xt, xteam]
permissions:
    xteam.core.user.accept:
        description: Allows team users to accept an invitation
        default: false
    xteam.core.user.chat:
        description: Allows team users to chat/msg their team
        default: false
    xteam.core.user.create:
        description: Allows team users to create a team
        default: false
    xteam.core.user.headquarters:
        description: Allows team users to teleport to headquarters
        default: false
    xteam.core.user.info:
        description: Allows team users view team info
        default: false
    xteam.core.user.join:
        description: Allows team users to join a team
        default: false
    xteam.core.user.leave:
        description: Allows team users to leave a team
        default: false
    xteam.core.user.list:
        description: Allows team users to list all team names
        default: false
    xteam.core.user.return:
        description: Allows team users to return to saved location
        default: false
    xteam.core.user.rally:
        description: Allows team users to rally to a location
        default: false
    xteam.core.user.tele:
        description: Allows team users to teleport to teammates
        default: false
    xteam.core.user.*:
        description: All team user core commands
        default: false
        children:
            xteam.core.user.accept: true
            xteam.core.user.chat: true
            xteam.core.user.create: true
            xteam.core.user.hq: true
            xteam.core.user.join: true
            xteam.core.user.leave: true
            xteam.core.user.list: true
            xteam.core.user.return: true
            xteam.core.user.rally: true
            xteam.core.user.tele: true
    xteam.core.admin.invite:
        description: Allows team admins to invite other players
        default: false
    xteam.core.admin.promote:
        description: Allows team admins to promote teammates
        default: false
    xteam.core.admin.sethq:
        description: Allows team admins to set a headquarters
        default: false
    xteam.core.admin.*:
        description: All team admin core commands
        default: false
        children:
            xteam.core.admin.invite: true
            xteam.core.admin.promote: true
            xteam.core.admin.sethq: true
    xteam.core.leader.demote:
        description: Allows team leaders to demote teammates
        default: false
    xteam.core.leader.disband:
        description: Allows team leaders to disband a team
        default: false
    xteam.core.leader.open:
        description: Allows team leaders to open team to public
        default: false
    xteam.core.leader.remove:
        description: Allows team leaders to remove players
        default: false
    xteam.core.leader.rename:
        description: Allows team leaders to rename team
        default: false
    xteam.core.leader.setleader:
        description: Allows team leaders to set leader of team
        default: false
    xteam.core.leader.setrally:
        description: Allows team leaders to set rally point for the team
        default: false
    xteam.core.leader.tag:
        description: Allows team leaders to set team tag
        default: false
    xteam.core.leader.*:
        description: All team leader core commands
        default: false
        children:
            xteam.core.leader.demote: true
            xteam.core.leader.disband: true
            xteam.core.leader.open: true
            xteam.core.leader.remove: true
            xteam.core.leader.rename: true
            xteam.core.leader.setleader: true
            xteam.core.leader.setrally: true
            xteam.core.leader.tag: true
    xteam.core.serveradmin.chatspy:
        description: Allows server admins to spy on team chat
        default: op
    xteam.core.serveradmin.debug:
        description: Allows server admins to debug the plugin
        default: op
    xteam.core.serveradmin.disband:
        description: Allows server admins to disband a team
        default: op
    xteam.core.serveradmin.demote:
        description: Allows server admins to demote a player on a team
        default: op
    xteam.core.serveradmin.hq:
        description: Allows server admins to teleport to any headquarters
        default: op
    xteam.core.serveradmin.promote:
        description: Allows server admins to promote a player on a team
        default: op
    xteam.core.serveradmin.reload:
        description: Allows server admins to reload the configuration file
        default: op
    xteam.core.serveradmin.remove:
        description: Allows server admins to remove player from a team
        default: op
    xteam.core.serveradmin.rename:
        description: Allows server admins to rename a team
        default: op
    xteam.core.serveradmin.tag:
        description: Allows server admins to set team tag
        default: op
    xteam.core.serveradmin.open:
        description: Allows server admins to open a team to the public
        default: op
    xteam.core.serveradmin.set:
        description: Allows server admins to set the team of a player
        default: op
    xteam.core.serveradmin.sethq:
        description: Allows server admins to set the headquarters of a team
        default: op
    xteam.core.serveradmin.setleader:
        description: Allows server admins to set the leader of a team
        default: op
    xteam.core.serveradmin.teleallhq:
        description: Allows server admins to teleport everyone to their headquarters
        default: op
    xteam.core.serveradmin.tpall:
        description: Allows server admins to teleport a team to current location
        default: op
    xteam.core.serveradmin.*:
        description: All server admin commands
        default: false
        children:
            xteam.core.serveradmin.chatspy: true
            xteam.core.serveradmin.disband: true
            xteam.core.serveradmin.demote: true
            xteam.core.serveradmin.hq: true
            xteam.core.serveradmin.promote: true
            xteam.core.serveradmin.reload: true
            xteam.core.serveradmin.remove: true
            xteam.core.serveradmin.rename: true
            xteam.core.serveradmin.tag: true
            xteam.core.serveradmin.open: true
            xteam.core.serveradmin.set: true
            xteam.core.serveradmin.sethq: true
            xteam.core.serveradmin.setleader: true
            xteam.core.serveradmin.teleallhq: true
            xteam.core.serveradmin.tpall: true
    xteam.core.*:
        description: All core commands
        default: false
        children:
            xteam.core.user.*: true
            xteam.core.admin.*: true
            xteam.core.leader.*: true
            xteam.core.serveradmin.*: true
    