name: xTeam
main: me.protocos.xteam.xTeam
version: 1.7.8
author: protocos
softdepend: [PermissionsEx]
commands:
    team:
        description: Team commands
        usage: /<command>
        aliases: [xt, xteam]
permissions:
    xteam.player.core.accept:
        description: Allows team players to accept an invitation
        default: false
    xteam.player.core.chat:
        description: Allows team players to chat/msg their team
        default: false
    xteam.player.core.create:
        description: Allows team players to create a team
        default: false
    xteam.player.core.hq:
        description: Allows team players to teleport to headquarters
        default: false
    xteam.player.core.join:
        description: Allows team players to join a team
        default: false
    xteam.player.core.leave:
        description: Allows team players to leave a team
        default: false
    xteam.player.core.list:
        description: Allows team players to list all team names
        default: false
    xteam.player.core.return:
        description: Allows team players to return to saved location
        default: false
    xteam.player.core.rally:
        description: Allows team players to rally to a location
        default: false
    xteam.player.core.tele:
        description: Allows team players to teleport to teammates
        default: false
    xteam.player.core.*:
        description: All team player core commands
        default: false
        children:
            xteam.player.core.accept: true
            xteam.player.core.chat: true
            xteam.player.core.create: true
            xteam.player.core.hq: true
            xteam.player.core.join: true
            xteam.player.core.leave: true
            xteam.player.core.list: true
            xteam.player.core.return: true
            xteam.player.core.rally: true
            xteam.player.core.tele: true
#    xteam.player.locations.list:
#        description: List team locations
#        default: false
#    xteam.player.locations.track:
#        description: Track team location
#        default: false
#    xteam.player.locations.*:
#        description: All team player location commands
#        default: false
#        children:
#            xteam.player.locations.list: true
#            xteam.player.locations.track: true
    xteam.player.*:
        description: All team player commands
        default: false
        children:
            xteam.player.core.*: true
#            xteam.player.locations.*: true
    xteam.admin.core.invite:
        description: Allows team admins to invite other players
        default: false
    xteam.admin.core.promote:
        description: Allows team admins to promote teammates
        default: false
    xteam.admin.core.sethq:
        description: Allows team admins to set a headquarters
        default: false
    xteam.admin.core.*:
        description: All team admin core commands
        default: false
        children:
            xteam.admin.core.invite: true
            xteam.admin.core.promote: true
            xteam.admin.core.sethq: true
#    xteam.admin.locations.add:
#        description: Add team location
#        default: false
#    xteam.admin.locations.remove:
#        description: Remove team location
#        default: false
#    xteam.admin.locations.*:
#        description: All admin locations commands
#        default: false
#        children:
#            xteam.admin.locations.add: true
#            xteam.admin.locations.remove: true
    xteam.admin.*:
        description: All team admin commands
        default: false
        children:
            xteam.admin.core.*: true
#            xteam.admin.locations.*: true
    xteam.leader.core.demote:
        description: Allows team leaders to demote teammates
        default: false
    xteam.leader.core.disband:
        description: Allows team leaders to disband a team
        default: false
    xteam.leader.core.open:
        description: Allows team leaders to open team to public
        default: false
    xteam.leader.core.remove:
        description: Allows team leaders to remove players
        default: false
    xteam.leader.core.rename:
        description: Allows team leaders to rename team
        default: false
    xteam.leader.core.setleader:
        description: Allows team leaders to set leader of team
        default: false
    xteam.leader.core.setrally:
        description: Allows team leaders to set rally point for the team
        default: false
    xteam.leader.core.tag:
        description: Allows team leaders to set team tag
        default: false
    xteam.leader.core.*:
        description: All team leader core commands
        default: false
        children:
            xteam.leader.core.demote: true
            xteam.leader.core.disband: true
            xteam.leader.core.open: true
            xteam.leader.core.remove: true
            xteam.leader.core.rename: true
            xteam.leader.core.setleader: true
            xteam.leader.core.setrally: true
            xteam.leader.core.tag: true
    xteam.leader.*:
        description: All team leader commands
        default: false
        children:
            xteam.leader.core.*: true
    xteam.serveradmin.core.chatspy:
        description: Allows server admins to spy on team chat
        default: op
    xteam.serveradmin.core.disband:
        description: Allows server admins to disband a team
        default: op
    xteam.serveradmin.core.demote:
        description: Allows server admins to demote a player on a team
        default: op
    xteam.serveradmin.core.hq:
        description: Allows server admins to teleport to any headquarters
        default: op
    xteam.serveradmin.core.promote:
        description: Allows server admins to promote a player on a team
        default: op
    xteam.serveradmin.core.reload:
        description: Allows server admins to reload the configuration file
        default: op
    xteam.serveradmin.core.remove:
        description: Allows server admins to remove player from a team
        default: op
    xteam.serveradmin.core.rename:
        description: Allows server admins to rename a team
        default: op
    xteam.serveradmin.core.tag:
        description: Allows server admins to set team tag
        default: op
    xteam.serveradmin.core.open:
        description: Allows server admins to open a team to the public
        default: op
    xteam.serveradmin.core.set:
        description: Allows server admins to set the team of a player
        default: op
    xteam.serveradmin.core.sethq:
        description: Allows server admins to set the headquarters of a team
        default: op
    xteam.serveradmin.core.setleader:
        description: Allows server admins to set the leader of a team
        default: op
    xteam.serveradmin.core.teleallhq:
        description: Allows server admins to teleport everyone to their headquarters
        default: op
    xteam.serveradmin.core.tpall:
        description: Allows server admins to teleport a team to current location
        default: op
#    xteam.serveradmin.core.update:
#        description: Update players
#        default: op
    xteam.serveradmin.core.*:
        description: All server admin commands
        default: false
        children:
            xteam.serveradmin.core.chatspy: true
            xteam.serveradmin.core.disband: true
            xteam.serveradmin.core.demote: true
            xteam.serveradmin.core.hq: true
            xteam.serveradmin.core.promote: true
            xteam.serveradmin.core.reload: true
            xteam.serveradmin.core.remove: true
            xteam.serveradmin.core.rename: true
            xteam.serveradmin.core.tag: true
            xteam.serveradmin.core.open: true
            xteam.serveradmin.core.set: true
            xteam.serveradmin.core.sethq: true
            xteam.serveradmin.core.setleader: true
            xteam.serveradmin.core.teleallhq: true
            xteam.serveradmin.core.tpall: true
#            xteam.serveradmin.core.update: true
    xteam.serveradmin.*:
        description: All admin commands
        default: false
        children:
            xteam.serveradmin.core.*: true
    